from weasyprint import HTML
from pathlib import Path

def test_weasyprint():
    # Create a simple HTML string
    html_content = """
    <html>
        <body>
            <h1>Test PDF</h1>
            <p>This is a test PDF generated by WeasyPrint.</p>
        </body>
    </html>
    """
    
    # Generate the PDF
    output_dir = Path(__file__).parent / 'analysis_results'
    output_dir.mkdir(exist_ok=True)
    pdf_path = output_dir / 'test.pdf'
    
    try:
        HTML(string=html_content).write_pdf(str(pdf_path))
        print(f"PDF generated successfully at: {pdf_path}")
    except Exception as e:
        print(f"Error generating PDF: {str(e)}")

if __name__ == "__main__":
    test_weasyprint() 